- name: Configurar S3 e DynamoDB para Terraform
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Criar Bucket S3 para o estado do Terraform
      amazon.aws.s3_bucket:
        name: "picbank-terraform-state"
        state: present
        region: "us-east-1"
        versioning: yes
      register: s3_result

    - name: Exibir informações do Bucket S3
      debug:
        msg: "Bucket S3 criado: {{ s3_result }}"

    - name: Criar Tabela DynamoDB para locks do Terraform
      community.aws.dynamodb_table:
        name: "picbank-terraform-lock"
        state: present
        region: "us-east-1"
        hash_key_name: "LockID"
        hash_key_type: "STRING"
        billing_mode: "PAY_PER_REQUEST"
      register: dynamodb_result

    - name: Exibir informações da Tabela DynamoDB
      debug:
        msg: "Tabela DynamoDB criada: {{ dynamodb_result }}"
